# Launcher icon generation
name: wedlist
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+21

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^9.0.0
  cached_network_image: ^3.3.1
  cloud_firestore: ^6.0.3
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  dart_code_metrics_presets: ^2.25.0
  equatable: ^2.0.7
  file_picker: ^10.3.2
  firebase_analytics: ^12.0.4
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  firebase_crashlytics: ^5.0.3
  firebase_database: ^12.0.3
  firebase_storage: ^13.0.3
  fl_chart: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.0
  fpdart: ^1.1.1
  freezed_annotation: ^3.1.0
  get_it: ^8.0.3
  go_router: ^16.3.0
  google_fonts: ^6.2.1
  google_mobile_ads: ^6.0.0
  google_sign_in: ^6.2.1
  gradient_borders: ^1.0.1
  hugeicons: ^0.0.11
  image: ^4.5.4
  image_picker: ^1.2.0
  in_app_purchase: ^3.1.11
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.4.0
  meta: ^1.15.0
  mime: ^2.0.0
  shared_preferences: ^2.5.3
  sign_in_with_apple: ^7.0.1
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.7.0
  fake_cloud_firestore: ^4.0.0
  firebase_auth_mocks: ^0.15.1
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  mocktail: ^1.0.3
  very_good_analysis: ^9.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

dependency_overrides:
  vector_math: ^2.2.0
